const colours = [
  { name: "1c enterprise", color: "#814ccc" },
  { name: "4d", color: null },
  { name: "abap", color: "#e8274b" },
  { name: "actionscript", color: "#882b0f" },
  { name: "ada", color: "#02f88c" },
  { name: "agda", color: "#315665" },
  { name: "ags script", color: "#b9d9ff" },
  { name: "al", color: "#3aa2b5" },
  { name: "alloy", color: "#64c800" },
  { name: "alpine abuild", color: null },
  { name: "ampl", color: "#e6efbb" },
  { name: "angelscript", color: "#c7d7dc" },
  { name: "antlr", color: "#9dc3ff" },
  { name: "apex", color: "#1797c0" },
  { name: "api blueprint", color: "#2acca8" },
  { name: "apl", color: "#5a8164" },
  { name: "apollo guidance computer", color: "#0b3d91" },
  { name: "applescript", color: "#101f1f" },
  { name: "arc", color: "#aa2afe" },
  { name: "asl", color: null },
  { name: "asp.net", color: "#9400ff" },
  { name: "aspectj", color: "#a957b0" },
  { name: "assembly", color: "#6e4c13" },
  { name: "asymptote", color: "#ff0000" },
  { name: "ats", color: "#1ac620" },
  { name: "augeas", color: null },
  { name: "autohotkey", color: "#6594b9" },
  { name: "autoit", color: "#1c3552" },
  { name: "awk", color: null },
  { name: "ballerina", color: "#ff5000" },
  { name: "batchfile", color: "#c1f12e" },
  { name: "befunge", color: null },
  { name: "bison", color: "#6a463f" },
  { name: "bitbake", color: null },
  { name: "blade", color: "#f7523f" },
  { name: "blitzbasic", color: null },
  { name: "blitzmax", color: "#cd6400" },
  { name: "bluespec", color: null },
  { name: "boo", color: "#d4bec1" },
  { name: "brainfuck", color: "#2f2530" },
  { name: "brightscript", color: null },
  { name: "c", color: "#555555" },
  { name: "c#", color: "#178600" },
  { name: "c++", color: "#f34b7d" },
  { name: "c2hs haskell", color: null },
  { name: "cap'n proto", color: null },
  { name: "cartocss", color: null },
  { name: "ceylon", color: "#dfa535" },
  { name: "chapel", color: "#8dc63f" },
  { name: "charity", color: null },
  { name: "chuck", color: null },
  { name: "cirru", color: "#ccccff" },
  { name: "clarion", color: "#db901e" },
  { name: "classic asp", color: "#6a40fd" },
  { name: "clean", color: "#3f85af" },
  { name: "click", color: "#e4e6f3" },
  { name: "clips", color: null },
  { name: "clojure", color: "#db5855" },
  { name: "cmake", color: null },
  { name: "cobol", color: null },
  { name: "codeql", color: null },
  { name: "coffeescript", color: "#244776" },
  { name: "coldfusion", color: "#ed2cd6" },
  { name: "coldfusion cfc", color: "#ed2cd6" },
  { name: "common lisp", color: "#3fb68b" },
  { name: "common workflow language", color: "#b5314c" },
  { name: "component pascal", color: "#b0ce4e" },
  { name: "cool", color: null },
  { name: "coq", color: null },
  { name: "crystal", color: "#000100" },
  { name: "cson", color: "#244776" },
  { name: "csound", color: null },
  { name: "csound document", color: null },
  { name: "csound score", color: null },
  { name: "css", color: "#563d7c" },
  { name: "cuda", color: "#3a4e3a" },
  { name: "cweb", color: null },
  { name: "cycript", color: null },
  { name: "cython", color: null },
  { name: "d", color: "#ba595e" },
  { name: "dafny", color: "#ffec25" },
  { name: "dart", color: "#00b4ab" },
  { name: "dataweave", color: "#003a52" },
  { name: "dhall", color: "#dfafff" },
  { name: "digital command language", color: null },
  { name: "dm", color: "#447265" },
  { name: "dockerfile", color: "#384d54" },
  { name: "dogescript", color: "#cca760" },
  { name: "dtrace", color: null },
  { name: "dylan", color: "#6c616e" },
  { name: "e", color: "#ccce35" },
  { name: "ec", color: "#913960" },
  { name: "ecl", color: "#8a1267" },
  { name: "eclipse", color: null },
  { name: "eiffel", color: "#4d6977" },
  { name: "ejs", color: "#a91e50" },
  { name: "elixir", color: "#6e4a7e" },
  { name: "elm", color: "#60b5cc" },
  { name: "emacs lisp", color: "#c065db" },
  { name: "emberscript", color: "#fff4f3" },
  { name: "eq", color: "#a78649" },
  { name: "erlang", color: "#b83998" },
  { name: "f#", color: "#b845fc" },
  { name: "f*", color: "#572e30" },
  { name: "factor", color: "#636746" },
  { name: "fancy", color: "#7b9db4" },
  { name: "fantom", color: "#14253c" },
  { name: "faust", color: "#c37240" },
  { name: "filebench wml", color: null },
  { name: "filterscript", color: null },
  { name: "fish", color: null },
  { name: "flux", color: "#88ccff" },
  { name: "forth", color: "#341708" },
  { name: "fortran", color: "#4d41b1" },
  { name: "fortran free form", color: null },
  { name: "freemarker", color: "#0050b2" },
  { name: "frege", color: "#00cafe" },
  { name: "futhark", color: "#5f021f" },
  { name: "g-code", color: "#d08cf2" },
  { name: "game maker language", color: "#71b417" },
  { name: "gaml", color: "#ffc766" },
  { name: "gams", color: null },
  { name: "gap", color: null },
  { name: "gcc machine description", color: null },
  { name: "gdb", color: null },
  { name: "gdscript", color: "#355570" },
  { name: "genie", color: "#fb855d" },
  { name: "genshi", color: null },
  { name: "gentoo ebuild", color: null },
  { name: "gentoo eclass", color: null },
  { name: "gherkin", color: "#5b2063" },
  { name: "glsl", color: null },
  { name: "glyph", color: "#c1ac7f" },
  { name: "gnuplot", color: "#f0a9f0" },
  { name: "go", color: "#00add8" },
  { name: "golo", color: "#88562a" },
  { name: "gosu", color: "#82937f" },
  { name: "grace", color: null },
  { name: "grammatical framework", color: "#ff0000" },
  { name: "graphql", color: "#e10098" },
  { name: "groovy", color: "#e69f56" },
  { name: "groovy server pages", color: null },
  { name: "hack", color: "#878787" },
  { name: "haml", color: "#ece2a9" },
  { name: "handlebars", color: "#f7931e" },
  { name: "harbour", color: "#0e60e3" },
  { name: "haskell", color: "#5e5086" },
  { name: "haxe", color: "#df7900" },
  { name: "hcl", color: null },
  { name: "hiveql", color: "#dce200" },
  { name: "hlsl", color: null },
  { name: "holyc", color: "#ffefaf" },
  { name: "html", color: "#e34c26" },
  { name: "hy", color: "#7790b2" },
  { name: "hyphy", color: null },
  { name: "idl", color: "#a3522f" },
  { name: "idris", color: "#b30000" },
  { name: "igor pro", color: "#0000cc" },
  { name: "inform 7", color: null },
  { name: "inno setup", color: null },
  { name: "io", color: "#a9188d" },
  { name: "ioke", color: "#078193" },
  { name: "isabelle", color: "#fefe00" },
  { name: "isabelle root", color: null },
  { name: "j", color: "#9eedff" },
  { name: "jasmin", color: null },
  { name: "java", color: "#b07219" },
  { name: "java server pages", color: null },
  { name: "javascript", color: "#f1e05a" },
  { name: "javascript+erb", color: null },
  { name: "jflex", color: "#dbca00" },
  { name: "jison", color: null },
  { name: "jison lex", color: null },
  { name: "jolie", color: "#843179" },
  { name: "jsoniq", color: "#40d47e" },
  { name: "jsonnet", color: "#0064bd" },
  { name: "jsx", color: null },
  { name: "julia", color: "#a270ba" },
  { name: "jupyter notebook", color: "#da5b0b" },
  { name: "kaitai struct", color: "#773b37" },
  { name: "kotlin", color: "#f18e33" },
  { name: "krl", color: "#28430a" },
  { name: "labview", color: null },
  { name: "lasso", color: "#999999" },
  { name: "latte", color: "#f2a542" },
  { name: "lean", color: null },
  { name: "less", color: "#1d365d" },
  { name: "lex", color: "#dbca00" },
  { name: "lfe", color: "#4c3023" },
  { name: "lilypond", color: null },
  { name: "limbo", color: null },
  { name: "literate agda", color: null },
  { name: "literate coffeescript", color: null },
  { name: "literate haskell", color: null },
  { name: "livescript", color: "#499886" },
  { name: "llvm", color: "#185619" },
  { name: "logos", color: null },
  { name: "logtalk", color: null },
  { name: "lolcode", color: "#cc9900" },
  { name: "lookml", color: "#652b81" },
  { name: "loomscript", color: null },
  { name: "lsl", color: "#3d9970" },
  { name: "lua", color: "#000080" },
  { name: "m", color: null },
  { name: "m4", color: null },
  { name: "m4sugar", color: null },
  { name: "macaulay2", color: "#d8ffff" },
  { name: "makefile", color: "#427819" },
  { name: "mako", color: null },
  { name: "markdown", color: "#083fa1" },
  { name: "marko", color: "#42bff2" },
  { name: "mask", color: "#f97732" },
  { name: "mathematica", color: null },
  { name: "matlab", color: "#e16737" },
  { name: "max", color: "#c4a79c" },
  { name: "maxscript", color: "#00a6a6" },
  { name: "mcfunction", color: "#e22837" },
  { name: "mercury", color: "#ff2b2b" },
  { name: "meson", color: "#007800" },
  { name: "metal", color: "#8f14e9" },
  { name: "minid", color: null },
  { name: "mirah", color: "#c7a938" },
  { name: "mirc script", color: "#3d57c3" },
  { name: "mlir", color: "#5ec8db" },
  { name: "modelica", color: null },
  { name: "modula-2", color: null },
  { name: "modula-3", color: "#223388" },
  { name: "module management system", color: null },
  { name: "monkey", color: null },
  { name: "moocode", color: null },
  { name: "moonscript", color: null },
  { name: "motorola 68k assembly", color: null },
  { name: "mql4", color: "#62a8d6" },
  { name: "mql5", color: "#4a76b8" },
  { name: "mtml", color: "#b7e1f4" },
  { name: "muf", color: null },
  { name: "mupad", color: null },
  { name: "myghty", color: null },
  { name: "nasl", color: null },
  { name: "ncl", color: "#28431f" },
  { name: "nearley", color: "#990000" },
  { name: "nemerle", color: "#3d3c6e" },
  { name: "nesc", color: "#94b0c7" },
  { name: "netlinx", color: "#0aa0ff" },
  { name: "netlinx+erb", color: "#747faa" },
  { name: "netlogo", color: "#ff6375" },
  { name: "newlisp", color: "#87aed7" },
  { name: "nextflow", color: "#3ac486" },
  { name: "nim", color: "#ffc200" },
  { name: "nit", color: "#009917" },
  { name: "nix", color: "#7e7eff" },
  { name: "nsis", color: null },
  { name: "nu", color: "#c9df40" },
  { name: "numpy", color: "#9c8af9" },
  { name: "objective-c", color: "#438eff" },
  { name: "objective-c++", color: "#6866fb" },
  { name: "objective-j", color: "#ff0c5a" },
  { name: "objectscript", color: "#424893" },
  { name: "ocaml", color: "#3be133" },
  { name: "odin", color: "#60affe" },
  { name: "omgrofl", color: "#cabbff" },
  { name: "ooc", color: "#b0b77e" },
  { name: "opa", color: null },
  { name: "opal", color: "#f7ede0" },
  { name: "open policy agent", color: null },
  { name: "opencl", color: null },
  { name: "openedge abl", color: null },
  { name: "openqasm", color: "#aa70ff" },
  { name: "openrc runscript", color: null },
  { name: "openscad", color: null },
  { name: "ox", color: null },
  { name: "oxygene", color: "#cdd0e3" },
  { name: "oz", color: "#fab738" },
  { name: "p4", color: "#7055b5" },
  { name: "pan", color: "#cc0000" },
  { name: "papyrus", color: "#6600cc" },
  { name: "parrot", color: "#f3ca0a" },
  { name: "parrot assembly", color: null },
  { name: "parrot internal representation", color: null },
  { name: "pascal", color: "#e3f171" },
  { name: "pawn", color: "#dbb284" },
  { name: "pep8", color: "#c76f5b" },
  { name: "perl", color: "#0298c3" },
  { name: "php", color: "#4f5d95" },
  { name: "picolisp", color: null },
  { name: "piglatin", color: "#fcd7de" },
  { name: "pike", color: "#005390" },
  { name: "plpgsql", color: null },
  { name: "plsql", color: "#dad8d8" },
  { name: "pogoscript", color: "#d80074" },
  { name: "pony", color: null },
  { name: "postscript", color: "#da291c" },
  { name: "pov-ray sdl", color: null },
  { name: "powerbuilder", color: "#8f0f8d" },
  { name: "powershell", color: "#012456" },
  { name: "prisma", color: "#0c344b" },
  { name: "processing", color: "#0096d8" },
  { name: "prolog", color: "#74283c" },
  { name: "propeller spin", color: "#7fa2a7" },
  { name: "pug", color: "#a86454" },
  { name: "puppet", color: "#302b6d" },
  { name: "purebasic", color: "#5a6986" },
  { name: "purescript", color: "#1d222d" },
  { name: "python", color: "#3572a5" },
  { name: "python console", color: null },
  { name: "q", color: "#0040cd" },
  { name: "q#", color: "#fed659" },
  { name: "qmake", color: null },
  { name: "qml", color: "#44a51c" },
  { name: "qt script", color: "#00b841" },
  { name: "quake", color: "#882233" },
  { name: "r", color: "#198ce7" },
  { name: "racket", color: "#3c5caa" },
  { name: "ragel", color: "#9d5200" },
  { name: "raku", color: "#0000fb" },
  { name: "raml", color: "#77d9fb" },
  { name: "rascal", color: "#fffaa0" },
  { name: "realbasic", color: null },
  { name: "reason", color: "#ff5847" },
  { name: "rebol", color: "#358a5b" },
  { name: "red", color: "#f50000" },
  { name: "redcode", color: null },
  { name: "ren'py", color: "#ff7f7f" },
  { name: "renderscript", color: null },
  { name: "rexx", color: null },
  { name: "ring", color: "#2d54cb" },
  { name: "riot", color: "#a71e49" },
  { name: "robotframework", color: null },
  { name: "roff", color: "#ecdebe" },
  { name: "rouge", color: "#cc0088" },
  { name: "rpc", color: null },
  { name: "ruby", color: "#701516" },
  { name: "runoff", color: "#665a4e" },
  { name: "rust", color: "#dea584" },
  { name: "sage", color: null },
  { name: "saltstack", color: "#646464" },
  { name: "sas", color: "#b34936" },
  { name: "sass", color: "#a53b70" },
  { name: "scala", color: "#c22d40" },
  { name: "scheme", color: "#1e4aec" },
  { name: "scilab", color: null },
  { name: "scss", color: "#c6538c" },
  { name: "sed", color: "#64b970" },
  { name: "self", color: "#0579aa" },
  { name: "shaderlab", color: null },
  { name: "shell", color: "#89e051" },
  { name: "shellsession", color: null },
  { name: "shen", color: "#120f14" },
  { name: "sieve", color: null },
  { name: "slash", color: "#007eff" },
  { name: "slice", color: "#003fa2" },
  { name: "slim", color: "#2b2b2b" },
  { name: "smali", color: null },
  { name: "smalltalk", color: "#596706" },
  { name: "smarty", color: null },
  { name: "smpl", color: "#c94949" },
  { name: "smt", color: null },
  { name: "solidity", color: "#aa6746" },
  { name: "sourcepawn", color: "#f69e1d" },
  { name: "sqf", color: "#3f3f3f" },
  { name: "sqlpl", color: null },
  { name: "squirrel", color: "#800000" },
  { name: "srecode template", color: "#348a34" },
  { name: "stan", color: "#b2011d" },
  { name: "standard ml", color: "#dc566d" },
  { name: "starlark", color: "#76d275" },
  { name: "stata", color: null },
  { name: "stylus", color: "#ff6347" },
  { name: "supercollider", color: "#46390b" },
  { name: "svelte", color: "#ff3e00" },
  { name: "svg", color: "#ff9900" },
  { name: "swift", color: "#ffac45" },
  { name: "swig", color: null },
  { name: "systemverilog", color: "#dae1c2" },
  { name: "tcl", color: "#e4cc98" },
  { name: "tcsh", color: null },
  { name: "terra", color: "#00004c" },
  { name: "tex", color: "#3d6117" },
  { name: "thrift", color: null },
  { name: "ti program", color: "#a0aa87" },
  { name: "tla", color: null },
  { name: "tsql", color: null },
  { name: "tsx", color: null },
  { name: "turing", color: "#cf142b" },
  { name: "twig", color: "#c1d026" },
  { name: "txl", color: null },
  { name: "typescript", color: "#2b7489" },
  { name: "unified parallel c", color: "#4e3617" },
  { name: "unix assembly", color: null },
  { name: "uno", color: "#9933cc" },
  { name: "unrealscript", color: "#a54c4d" },
  { name: "urweb", color: null },
  { name: "v", color: "#4f87c4" },
  { name: "vala", color: "#fbe5cd" },
  { name: "vba", color: "#867db1" },
  { name: "vbscript", color: "#15dcdc" },
  { name: "vcl", color: "#148aa8" },
  { name: "verilog", color: "#b2b7f8" },
  { name: "vhdl", color: "#adb2cb" },
  { name: "vim script", color: "#199f4b" },
  { name: "visual basic .net", color: "#945db7" },
  { name: "volt", color: "#1f1f1f" },
  { name: "vue", color: "#2c3e50" },
  { name: "wdl", color: "#42f1f4" },
  { name: "webassembly", color: "#04133b" },
  { name: "webidl", color: null },
  { name: "wisp", color: "#7582d1" },
  { name: "wollok", color: "#a23738" },
  { name: "x10", color: "#4b6bef" },
  { name: "xbase", color: "#403a40" },
  { name: "xc", color: "#99da07" },
  { name: "xojo", color: null },
  { name: "xproc", color: null },
  { name: "xquery", color: "#5232e7" },
  { name: "xs", color: null },
  { name: "xslt", color: "#eb8ceb" },
  { name: "xtend", color: null },
  { name: "yacc", color: "#4b6c4b" },
  { name: "yaml", color: "#cb171e" },
  { name: "yara", color: "#220000" },
  { name: "yasnippet", color: "#32ab90" },
  { name: "zap", color: "#0d665e" },
  { name: "zeek", color: null },
  { name: "zenscript", color: "#00bcd1" },
  { name: "zephir", color: "#118f9e" },
  { name: "zig", color: "#ec915c" },
  { name: "zil", color: "#dc75e5" },
  { name: "zimpl", color: null }
]

const githubColours = (language) => {
  let outputColour
  // eslint-disable-next-line
  colours.map((lang) => {
    if (lang.name === language) {
      outputColour = lang.color
    }
  })
  return outputColour
}
  export default githubColours